perms-for-custom-recipes: false
perms-for-vanilla-recipes: false
default-template-width: 3
default-template-height: 3
#the item to click to close the inventory
close:
  type: BARRIER
  meta:
     displayname: "§cClose"
  #the item around the crafting slots
background:
   type: STAINED_GLASS_PANE
   meta:
      data: 7
      displayname: " "
workbench:
  # Title of the GUI
  title: 'Crafting Table'
  # Size of the GUI, make sure you don't define slots above the size-1
  size: 45
  # Slots in which can be crafted
  crafting-slots:
    - 10
    - 11
    - 12
    - 19
    - 20
    - 21
    - 28
    - 29
    - 30
  close-slot: 40
  # Slots in which the state of the craft will be shown (invalid recipe/valid recipe)
  craft-state-slots:
    - 36
    - 37
    - 38
    - 39
    - 41
    - 42
    - 43
    - 44
  # Slot in which the crafting result will end up
  result-slot: 24    
recipe-create-gui:
  title: "Create Recipe"
  result-slot: 23
  shaped: 16
  save: 34
recipe-view-gui:
   title: "%r Recipe" #r = recipe name
   close-slot: 40
   back-slot: 39 
   next:
      type: ARROW
      meta:
         displayname: "§aNext Recipe"
         lore:
         - "§7Click to view the next recipe"
   previous:
      type: ARROW
      meta:
         displayname: "§aPrevious Recipe"
         lore:
         - "§7Click to view the previous recipe"
   back:
      commands:
      - "kill %p"
      type: ARROW
      meta:
         displayname: "§c§lBack"
         lore:
         - "§7Click to go back"