#the item to click to close the inventory
close:
  type: BARRIER
  meta:
     displayname: "§cClose"
  #the item around the crafting slots
background:
   type: STAINED_GLASS_PANE
   meta:
      data: 7
      displayname: " "
workbench:
  # Title of the GUI
  title: 'Crafting Table'
  # Size of the GUI, make sure you don't define slots above the size-1
  size: 54
  # Slots in which can be crafted
  crafting-slots:
  - 10
  - 11
  - 12
  - 19
  - 20
  - 21
  - 28
  - 29
  - 30
  close-slot: 49
  # Slots in which the state of the craft will be shown (invalid recipe/valid recipe)
  craft-state-slots:
    - 45
    - 46
    - 47
    - 48
    - 50
    - 51
    - 52
    - 53
  # Slot in which the crafting result will end up
  result-slot: 24    
recipe-create-gui:
  title: "Create Recipe"
  result-slot: 23
  shaped: 16
  save: 34