name: FancyCrafting
version: 4.10.0
main: de.ancash.fancycrafting.FancyCrafting
depend: [ILibrary, NBTNexus]
soft-depend: [CustomCrafting]
author: [Ancash]
api-version: 1.13

commands:
   fc:
      usage:
      - "§aFancyCrafting Commands:"
      - "§a/fc bl (open blacklist)"
      - "§a/fc blacklist (see above)"
      - "§7/fc reload"
      - "§7/fc open (open the crafting gui)"
      - "§7/fc open <1-8> <1-6>"
      - "§7/fc open <player>"
      - "§7/fc open <player> <1-8> <1-6>"
      - "§7/fc create (create a new recipe)"
      - "§7/fc edit (edit custom recipes)"
      - "§7/fc view (view all custom recipes)"
      - "§7/fc view <recipe-name> (view a recipe, replace ' ' with '-' in recipe name)"
      - "§7/fc acie (opens auto crafter item editor)"
      - "§7/fc acii (makes item in your hand auto crafter)"