name: FancyCrafting
version: 4.5.1
main: de.ancash.fancycrafting.FancyCrafting
depend: [ILibrary]
api-version: 1.13

commands:
   fc:
      usage:
      - "§aFancyCrafting Commands:"
      - "§7/fc reload"
      - "§7/fc open (open the crafting gui)"
      - "§7/fc open <1-8> <1-6>"
      - "§7/fc open <player>"
      - "§7/fc open <player> <1-8> <1-6>"
      - "§7/fc create (create a new recipe)"
      - "§7/fc edit (edit custom recipes)"
      - "§7/fc view (view all custom recipes)"
      - "§7/fc view <recipe-name> (view a recipe, replace ' ' with '-' in recipe name)"